-- Insert roles if they don't exist
INSERT INTO roles (name) 
SELECT 'ROLE_CUSTOMER' 
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_CUSTOMER');

INSERT INTO roles (name) 
SELECT 'ROLE_FLEET_MANAGER' 
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_FLEET_MANAGER');

INSERT INTO roles (name) 
SELECT 'ROLE_SYSTEM_ADMIN' 
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_SYSTEM_ADMIN');

INSERT INTO roles (name) 
SELECT 'ROLE_OWNER' 
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_OWNER');
